# Generated by Django 3.1.4 on 2021-01-03 01:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(default='', on_delete=models.SET(core.models.get_sentinel_user), to='core.pessoa'),
            preserve_default=False,
        ),
    ]
